### ISSUE TITLE
每个页面响应速度太慢

### ISSUE THREAD

**Issue by zhangpengju666** [wangl1989/mysiteforme#3]
LoginController.java line 168 String result = HttpUtil.get(mys.toString());
基本影响大部分页面打开速度慢6秒以上。
这个可以考虑放缓存吗？
另外的页面响应速度也不是很快。

**Comment by wangl1989** [comment]
LoginController.java  里数据请求已经优化,且代码已经更新
页面打开6秒略显夸张 我这边实地测试没有这么长时间的延时
页面响应不快的话 可能是我服务器只有1M的网速影响的浏览体验
